language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "$SONAR_ORG"
    token:
      secure: "$SONAR_TOKEN"
jdk:
  - openjdk8

script:
  - mvn clean verify sonar:sonar -Pcoverage
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Pcoverage -Dsonar.projectKey=sandorZHAO_mybatis-generator

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'